<?php
/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   Copyright (c) 2016 District Commerce (http://districtcommerce.com)
 * @license     http://store.districtcommerce.com/license
 *
 */

$acceptedCards = Mage::getStoreConfig('payment/stripe_cc/cctype');
?>

<link rel="stylesheet" href="/skin/frontend/base/default/css/district/stripe/styles.css">
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <input type="hidden" name="stripeToken" id="stripe_token">
    <div id="stripe-cards-select-new">
        <div id="stripe-card-element"></div>
        <!-- Used to display form errors -->
        <div id="stripe-card-errors" role="alert"></div>
    </div>
</div>

<script>

    var stripe = Stripe('<?php echo Mage::getStoreConfig('payment/stripe_cc/api_publishable_key'); ?>');

    (function() {
        district.stripeCc.init(stripe);
    })();

</script>
