<?php
/**
 * District Commerce
 *
 * @category    District
 * @package     Stripe
 * @author      District Commerce <support@districtcommerce.com>
 * @copyright   Copyright (c) 2016 District Commerce (http://districtcommerce.com)
 * @license     http://store.districtcommerce.com/license
 *
 */

$isStripeCustomer = false;
$savedCards = false;
$acceptedCards = Mage::getStoreConfig('payment/stripe_cc/cctype');
$acceptedCardsArr = explode(',', $acceptedCards);
$helper = Mage::helper('stripe');

//If customer exists in Stripe
if($cust = Mage::helper('stripe')->retrieveCustomer()) {

    //Set customer flag
    $isStripeCustomer = true;

    //Get stored cards
    $cards = $cust->sources->data;

    //If there are stored cards, set saved cards flag
    if(sizeof($cards) > 0) {
        $savedCards = true;
    }
}

?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div id="stripe-cards-select">
        <input type="hidden" name="stripeToken" id="stripe_token">
        <?php if($isStripeCustomer): ?>
        <input type="hidden" name="isStripeCustomer" value="1">
        <?php endif; ?>
        <?php if($savedCards): ?>
        <ol id="stripe-cards-select-saved">
            <li>
                <?php foreach($cards as $card): ?>
                    <label class="district-label">
                        <input type="radio" name="stripeSavedCard" value="<?php echo $card->id; ?>" style="display: none;">
                        <span class="district-cc district-cc-<?php echo $helper->getClassByName($card->brand); ?>" title="<?php echo $card->brand; ?>"><?php echo $card->brand; ?></span>
                        <?php echo $this->__('Ending in <strong>%s</strong>', $card->last4); ?>
                        (<?php echo $card->exp_month . '/' . substr($card->exp_year, 2); ?>)
                    </label>
                <?php endforeach; ?>
                <label class="district-label"><input type="radio" name="stripeSavedCard" value="" style="display: none;">
                    <span class="district-cc"><?php echo $this->__('New card'); ?></span>
                    <strong><?php echo $this->__('New card'); ?></strong>
                </label>
            </li>
        </ol>
        <?php endif; ?>
        <div id="stripe-cards-select-new" <?php if($savedCards): ?> style="display:none;"<?php endif; ?>>
            <div id="stripe-card-element"></div>

            <?php if(Mage::getSingleton('customer/session')->isLoggedIn() && Mage::getStoreConfig('payment/stripe_cc/save_cc_enabled')): ?>
                <div id="stripe-cards-select-save">
                    <label><input type="checkbox" name="stripeSaveCard" /> <?php echo $this->__('Save card'); ?></label>
                </div>
            <?php endif; ?>

            <!-- Used to display form errors -->
            <div id="stripe-card-errors" role="alert"></div>
        </div>

    </div>

    <?php if(sizeof($acceptedCardsArr) > 0): ?>
    <div id="stripe-cards-info">
    <?php foreach($acceptedCardsArr as $code): ?>
    <?php if($card = $helper->getCardInfoByCode($code)): ?>
        <span class="district-cc district-cc-<?php echo $card['class']; ?>" title="<?php echo $card['label']; ?>"><?php echo $card['label']; ?></span>
    <?php endif ;?>
    <?php endforeach; ?>
    </div>
    <?php endif; ?>

</div>

<script>

    var stripe = Stripe('<?php echo Mage::getStoreConfig('payment/stripe_cc/api_publishable_key'); ?>');

    (function() {
        district.stripeCc.init(stripe);
    })();

</script>
